app:
  baseURL: http://localhost:8080
  issuer: ${app.baseURL}
  jks:
    filePath: classpath:keystore/keystore.jks
    password: keypass123

spring:
  security:
    oauth2:
      resource:
        jwt:
          key-set-uri: ${app.baseURL}/.well-known/jwks.json
  application:
    name: languageWebs
  datasource:
    url: jdbc:postgresql://localhost:5432/languageWebs
    username: dev
    password: admin123
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
