app:
  secret_key: 2D4B6150645367566B597033733676397924423F4528482B4D6251655468576D
spring:
  application:
    name: languageWebs
  datasource:
    url: jdbc:postgresql://localhost:5432/languageWebs
    username: dev
    password: admin123
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
